# This is a basic workflow to help you get started with Run SOAtest Action

name: Parasoft SOAtest CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  test:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3
      
      - name: Run SOATest CLI 
        run: |
          #soatestcli -import $GITHUB_WORKSPACE/TestAssets
          #soatestcli -data D:\Jenkins_Integrations -resource /TestAssets/ -config "user://Example Configuration" -settings D:\Jenkins_Integrations\localsettings.properties
          #soatestcli -data $GITHUB_WORKSPACE -resource /TestAssets/ -config "user://Example Configuration" -settings ${{ github.workspace }}/localsettings.properties
          soatestcli -import ${PWD}/TestAssets/TestParabank
          soatestcli -data ${PWD} -resource /TestAssets/TestParabank/Parabank_APITests.tst -config "user://Example Configuration" -settings ${PWD}/localsettings.properties
          
          
     
