# This is a basic workflow to help you get started with Run SOAtest Action

name: Parasoft SOAtest CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  test:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v3

      # Runs SOAtest cli commands using the runner's shell
      - name: Run SOATest CLI 
        run: |
          soatestcli -data D:\Jenkins_Integrations -resource /TestAssets/ -config "user://Example Configuration" -settings D:\Jenkins_Integrations\localsettings.properties
      - name: Upload results (SARIF)
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
            sarif_file: reports/report.sarif # reports is a default location for reports directory
       - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: SOAtest reports
          path: reports/*.*

